# Generated by Django 3.0.6 on 2020-05-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyaltycard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('barcode_format', models.CharField(max_length=50)),
                ('barcode_content', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyaltycards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
