# Generated by Django 2.1.15 on 2020-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='device_registration_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
