# Generated by Django 3.0.6 on 2020-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='return_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='warranty_time',
            field=models.DateField(),
        ),
    ]
