# Generated by Django 3.0.6 on 2020-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_auto_20200601_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails'),
        ),
    ]
