# Generated by Django 3.0.6 on 2020-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_receipt_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='warranty_time',
        ),
        migrations.AddField(
            model_name='receipt',
            name='months_of_warranty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='weeks_to_return',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
